FROM mcr.microsoft.com/dotnet/sdk:5.0
WORKDIR /app



# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out

ENV ASPNETCORE_URLS http://*:80
# Build runtime image

ENTRYPOINT ["dotnet", "out/MVCVM.WebApp.dll"]